// <auto-generated />
using System;
using BinToBloom_Backend.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BinToBloom_Backend.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260203035630_AddPickupFrequencyField")]
    partial class AddPickupFrequencyField
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("BinToBloom_Backend.Models.Entities.Admin", b =>
                {
                    b.Property<int>("AdminId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("admin_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("AdminId"));

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("AdminId");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Admins");
                });

            modelBuilder.Entity("BinToBloom_Backend.Models.Entities.BusinessDetail", b =>
                {
                    b.Property<int>("BusinessId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("business_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("BusinessId"));

                    b.Property<string>("BusinessType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("business_type");

                    b.Property<bool>("PaymentEnabled")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("payment_enabled");

                    b.Property<string>("PickupFrequency")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("pickup_frequency");

                    b.Property<int>("SustainabilityScore")
                        .HasColumnType("int")
                        .HasColumnName("sustainability_score");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("BusinessId");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("BusinessDetails");
                });

            modelBuilder.Entity("BinToBloom_Backend.Models.Entities.Collector", b =>
                {
                    b.Property<int>("CollectorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("collector_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("CollectorId"));

                    b.Property<decimal?>("CurrentLat")
                        .HasColumnType("decimal(9,6)")
                        .HasColumnName("current_lat");

                    b.Property<decimal?>("CurrentLng")
                        .HasColumnType("decimal(9,6)")
                        .HasColumnName("current_lng");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("status");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("CollectorId");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Collectors");
                });

            modelBuilder.Entity("BinToBloom_Backend.Models.Entities.Contact", b =>
                {
                    b.Property<int>("ContactId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("contact_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ContactId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("email");

                    b.Property<bool>("IsRead")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_read");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("varchar(2000)")
                        .HasColumnName("message");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("name");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("subject");

                    b.HasKey("ContactId");

                    b.ToTable("Contacts");
                });

            modelBuilder.Entity("BinToBloom_Backend.Models.Entities.EcoReward", b =>
                {
                    b.Property<int>("RewardId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("reward_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("RewardId"));

                    b.Property<DateTime>("EarnedOn")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("earned_on");

                    b.Property<int>("PointsEarned")
                        .HasColumnType("int")
                        .HasColumnName("points_earned");

                    b.Property<string>("RewardType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("reward_type");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("RewardId");

                    b.HasIndex("UserId");

                    b.ToTable("EcoRewards");
                });

            modelBuilder.Entity("BinToBloom_Backend.Models.Entities.HouseholdDetail", b =>
                {
                    b.Property<int>("HouseholdId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("household_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("HouseholdId"));

                    b.Property<int>("EcoPoints")
                        .HasColumnType("int")
                        .HasColumnName("eco_points");

                    b.Property<int>("LeaderboardRank")
                        .HasColumnType("int")
                        .HasColumnName("leaderboard_rank");

                    b.Property<decimal>("TotalWasteKg")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("total_waste_kg");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("HouseholdId");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("HouseholdDetails");
                });

            modelBuilder.Entity("BinToBloom_Backend.Models.Entities.Leaderboard", b =>
                {
                    b.Property<int>("LeaderboardId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("leaderboard_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("LeaderboardId"));

                    b.Property<int>("Month")
                        .HasColumnType("int")
                        .HasColumnName("month");

                    b.Property<int>("Rank")
                        .HasColumnType("int")
                        .HasColumnName("rank");

                    b.Property<decimal>("TotalWaste")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("total_waste");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("LeaderboardId");

                    b.HasIndex("UserId");

                    b.ToTable("Leaderboard");
                });

            modelBuilder.Entity("BinToBloom_Backend.Models.Entities.NGO", b =>
                {
                    b.Property<int>("NGOId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ngo_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("NGOId"));

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("city");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("NGOId");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("NGOs");
                });

            modelBuilder.Entity("BinToBloom_Backend.Models.Entities.NGOReport", b =>
                {
                    b.Property<int>("ReportId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("report_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ReportId"));

                    b.Property<decimal>("CarbonSaved")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("carbon_saved");

                    b.Property<DateTime>("GeneratedOn")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("generated_on");

                    b.Property<int>("NGOId")
                        .HasColumnType("int")
                        .HasColumnName("ngo_id");

                    b.Property<decimal>("TotalWaste")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("total_waste");

                    b.HasKey("ReportId");

                    b.HasIndex("NGOId");

                    b.ToTable("NGOReports");
                });

            modelBuilder.Entity("BinToBloom_Backend.Models.Entities.Payment", b =>
                {
                    b.Property<int>("PaymentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("payment_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("PaymentId"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("amount");

                    b.Property<int>("BusinessId")
                        .HasColumnType("int")
                        .HasColumnName("business_id");

                    b.Property<DateTime>("PaymentDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("payment_date");

                    b.Property<string>("PaymentMode")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("payment_mode");

                    b.Property<string>("PaymentStatus")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("payment_status");

                    b.Property<int?>("PickupRequestId")
                        .HasColumnType("int")
                        .HasColumnName("pickup_request_id");

                    b.Property<string>("RazorpayOrderId")
                        .HasColumnType("longtext")
                        .HasColumnName("razorpay_order_id");

                    b.Property<string>("RazorpayPaymentId")
                        .HasColumnType("longtext")
                        .HasColumnName("razorpay_payment_id");

                    b.Property<string>("RazorpaySignature")
                        .HasColumnType("longtext")
                        .HasColumnName("razorpay_signature");

                    b.Property<int?>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("PaymentId");

                    b.HasIndex("BusinessId");

                    b.HasIndex("PickupRequestId")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("Payments");
                });

            modelBuilder.Entity("BinToBloom_Backend.Models.Entities.PickupRequest", b =>
                {
                    b.Property<int>("PickupId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("pickup_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("PickupId"));

                    b.Property<int?>("CollectorId")
                        .HasColumnType("int")
                        .HasColumnName("collector_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<decimal?>("Latitude")
                        .HasColumnType("decimal(10, 8)")
                        .HasColumnName("latitude");

                    b.Property<decimal?>("Longitude")
                        .HasColumnType("decimal(11, 8)")
                        .HasColumnName("longitude");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("notes");

                    b.Property<string>("PickupFrequency")
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("pickup_frequency");

                    b.Property<string>("PickupStatus")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("pickup_status");

                    b.Property<DateOnly>("ScheduledDate")
                        .HasColumnType("date")
                        .HasColumnName("scheduled_date");

                    b.Property<TimeOnly>("ScheduledTime")
                        .HasColumnType("time(6)")
                        .HasColumnName("scheduled_time");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.Property<string>("WasteType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("waste_type");

                    b.HasKey("PickupId");

                    b.HasIndex("CollectorId");

                    b.HasIndex("UserId");

                    b.ToTable("PickupRequests");
                });

            modelBuilder.Entity("BinToBloom_Backend.Models.Entities.Role", b =>
                {
                    b.Property<int>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("role_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("RoleId"));

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("role_name");

                    b.HasKey("RoleId");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("BinToBloom_Backend.Models.Entities.TrackingLog", b =>
                {
                    b.Property<int>("TrackId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("track_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("TrackId"));

                    b.Property<decimal>("Latitude")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("latitude");

                    b.Property<decimal>("Longitude")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("longitude");

                    b.Property<int>("PickupId")
                        .HasColumnType("int")
                        .HasColumnName("pickup_id");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("timestamp");

                    b.HasKey("TrackId");

                    b.HasIndex("PickupId");

                    b.ToTable("TrackingLogs");
                });

            modelBuilder.Entity("BinToBloom_Backend.Models.Entities.WasteLog", b =>
                {
                    b.Property<int>("LogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("log_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("LogId"));

                    b.Property<DateTime>("CollectedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("collected_at");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("notes");

                    b.Property<string>("PhotoUrl")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("photo_url");

                    b.Property<int>("PickupId")
                        .HasColumnType("int")
                        .HasColumnName("pickup_id");

                    b.Property<string>("WasteType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("waste_type");

                    b.Property<decimal>("WeightKg")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("weight_kg");

                    b.HasKey("LogId");

                    b.HasIndex("PickupId");

                    b.ToTable("WasteLogs");
                });

            modelBuilder.Entity("User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("UserId"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("varchar(500)")
                        .HasColumnName("address");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("varchar(100)")
                        .HasColumnName("city");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("email");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(100)")
                        .HasColumnName("name");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("password");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("varchar(15)")
                        .HasColumnName("phone");

                    b.Property<int>("RoleId")
                        .HasColumnType("int")
                        .HasColumnName("role_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("varchar(10)")
                        .HasColumnName("status");

                    b.HasKey("UserId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("RoleId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("BinToBloom_Backend.Models.Entities.Admin", b =>
                {
                    b.HasOne("User", "User")
                        .WithOne("Admin")
                        .HasForeignKey("BinToBloom_Backend.Models.Entities.Admin", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("BinToBloom_Backend.Models.Entities.BusinessDetail", b =>
                {
                    b.HasOne("User", "User")
                        .WithOne("BusinessDetail")
                        .HasForeignKey("BinToBloom_Backend.Models.Entities.BusinessDetail", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("BinToBloom_Backend.Models.Entities.Collector", b =>
                {
                    b.HasOne("User", "User")
                        .WithOne("Collector")
                        .HasForeignKey("BinToBloom_Backend.Models.Entities.Collector", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("BinToBloom_Backend.Models.Entities.EcoReward", b =>
                {
                    b.HasOne("User", "User")
                        .WithMany("EcoRewards")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("BinToBloom_Backend.Models.Entities.HouseholdDetail", b =>
                {
                    b.HasOne("User", "User")
                        .WithOne("HouseholdDetail")
                        .HasForeignKey("BinToBloom_Backend.Models.Entities.HouseholdDetail", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("BinToBloom_Backend.Models.Entities.Leaderboard", b =>
                {
                    b.HasOne("User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("BinToBloom_Backend.Models.Entities.NGO", b =>
                {
                    b.HasOne("User", "User")
                        .WithOne("NGO")
                        .HasForeignKey("BinToBloom_Backend.Models.Entities.NGO", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("BinToBloom_Backend.Models.Entities.NGOReport", b =>
                {
                    b.HasOne("BinToBloom_Backend.Models.Entities.NGO", "NGO")
                        .WithMany("NGOReports")
                        .HasForeignKey("NGOId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NGO");
                });

            modelBuilder.Entity("BinToBloom_Backend.Models.Entities.Payment", b =>
                {
                    b.HasOne("BinToBloom_Backend.Models.Entities.BusinessDetail", "BusinessDetail")
                        .WithMany("Payments")
                        .HasForeignKey("BusinessId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BinToBloom_Backend.Models.Entities.PickupRequest", "PickupRequest")
                        .WithOne("Payment")
                        .HasForeignKey("BinToBloom_Backend.Models.Entities.Payment", "PickupRequestId");

                    b.HasOne("User", "User")
                        .WithMany()
                        .HasForeignKey("UserId");

                    b.Navigation("BusinessDetail");

                    b.Navigation("PickupRequest");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BinToBloom_Backend.Models.Entities.PickupRequest", b =>
                {
                    b.HasOne("BinToBloom_Backend.Models.Entities.Collector", "Collector")
                        .WithMany("PickupRequests")
                        .HasForeignKey("CollectorId");

                    b.HasOne("User", "User")
                        .WithMany("PickupRequests")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Collector");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BinToBloom_Backend.Models.Entities.TrackingLog", b =>
                {
                    b.HasOne("BinToBloom_Backend.Models.Entities.PickupRequest", "PickupRequest")
                        .WithMany("TrackingLogs")
                        .HasForeignKey("PickupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PickupRequest");
                });

            modelBuilder.Entity("BinToBloom_Backend.Models.Entities.WasteLog", b =>
                {
                    b.HasOne("BinToBloom_Backend.Models.Entities.PickupRequest", "PickupRequest")
                        .WithMany("WasteLogs")
                        .HasForeignKey("PickupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PickupRequest");
                });

            modelBuilder.Entity("User", b =>
                {
                    b.HasOne("BinToBloom_Backend.Models.Entities.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("BinToBloom_Backend.Models.Entities.BusinessDetail", b =>
                {
                    b.Navigation("Payments");
                });

            modelBuilder.Entity("BinToBloom_Backend.Models.Entities.Collector", b =>
                {
                    b.Navigation("PickupRequests");
                });

            modelBuilder.Entity("BinToBloom_Backend.Models.Entities.NGO", b =>
                {
                    b.Navigation("NGOReports");
                });

            modelBuilder.Entity("BinToBloom_Backend.Models.Entities.PickupRequest", b =>
                {
                    b.Navigation("Payment");

                    b.Navigation("TrackingLogs");

                    b.Navigation("WasteLogs");
                });

            modelBuilder.Entity("BinToBloom_Backend.Models.Entities.Role", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("User", b =>
                {
                    b.Navigation("Admin");

                    b.Navigation("BusinessDetail");

                    b.Navigation("Collector");

                    b.Navigation("EcoRewards");

                    b.Navigation("HouseholdDetail");

                    b.Navigation("NGO");

                    b.Navigation("PickupRequests");
                });
#pragma warning restore 612, 618
        }
    }
}
